package com.crm.entity.enums;

public enum AutomationEventType {
    LEAD_CREATED,
    LEAD_UPDATED,
    DEAL_CREATED,
    DEAL_UPDATED,
    CAMPAIGN_ATTRIBUTED_LEAD,
    CASE_CREATED,
    CASE_BREACHED,
    CUSTOMER_UPDATED,
    GOVERNANCE_DIGEST_DUE,
    SCHEDULED
}
