ALTER TABLE workflow_rules
    ADD COLUMN IF NOT EXISTS review_stalled_deals BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS review_high_risk_deals BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS review_overdue_next_steps BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS review_territory_mismatch BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS stalled_deal_days INTEGER NOT NULL DEFAULT 14,
    ADD COLUMN IF NOT EXISTS rescue_task_due_days INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS rescue_task_priority VARCHAR(20) NOT NULL DEFAULT 'HIGH';
