ALTER TABLE workflow_rules
    ADD COLUMN IF NOT EXISTS include_watch_reps BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS include_at_risk_reps BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS watch_task_due_days INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS at_risk_task_due_days INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS watch_task_priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    ADD COLUMN IF NOT EXISTS at_risk_task_priority VARCHAR(20) NOT NULL DEFAULT 'HIGH';
