ALTER TABLE workflow_rules
    ADD COLUMN IF NOT EXISTS digest_cadence_days INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS digest_task_due_days INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS digest_task_priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    ADD COLUMN IF NOT EXISTS elevate_digest_for_sla_breaches BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS watch_review_days INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS high_review_days INTEGER NOT NULL DEFAULT 3,
    ADD COLUMN IF NOT EXISTS critical_review_days INTEGER NOT NULL DEFAULT 5,
    ADD COLUMN IF NOT EXISTS overdue_review_task_priority VARCHAR(20) NOT NULL DEFAULT 'HIGH',
    ADD COLUMN IF NOT EXISTS overdue_escalation_task_due_days INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS overdue_escalation_task_priority VARCHAR(20) NOT NULL DEFAULT 'HIGH';
