-- V3: Enable pgvector extension and add vector column

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding vector column to embeddings table (384 dimensions for all-MiniLM-L6-v2)
ALTER TABLE embeddings ADD COLUMN embedding vector(384);

-- Create vector similarity index using HNSW (Hierarchical Navigable Small World)
-- This provides fast approximate nearest neighbor search
CREATE INDEX idx_embeddings_vector ON embeddings 
USING hnsw (embedding vector_cosine_ops);

-- Alternative: IVFFlat index (can be used instead of HNSW for smaller datasets)
-- CREATE INDEX idx_embeddings_vector ON embeddings 
-- USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- Add comment for documentation
COMMENT ON COLUMN embeddings.embedding IS 'Vector embedding (384 dimensions) generated by all-MiniLM-L6-v2 model';
