ALTER TABLE products
    ADD COLUMN IF NOT EXISTS minimum_price NUMERIC(19,2),
    ADD COLUMN IF NOT EXISTS allow_discounting BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS max_discount_percent NUMERIC(5,2) DEFAULT 100,
    ADD COLUMN IF NOT EXISTS is_configurable BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE quotes
    ADD COLUMN IF NOT EXISTS pricing_approval_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS pricing_approval_reason TEXT,
    ADD COLUMN IF NOT EXISTS pricing_approved_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS pricing_approved_by UUID;
