ALTER TABLE products
    ADD COLUMN IF NOT EXISTS bundle_only BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS minimum_quantity INTEGER,
    ADD COLUMN IF NOT EXISTS maximum_quantity INTEGER,
    ADD COLUMN IF NOT EXISTS bundle_size INTEGER NOT NULL DEFAULT 1;

