ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS marketing_consent BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS consent_captured_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS consent_source VARCHAR(120),
    ADD COLUMN IF NOT EXISTS privacy_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS data_quality_score INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS enrichment_status VARCHAR(30) NOT NULL DEFAULT 'NOT_ENRICHED',
    ADD COLUMN IF NOT EXISTS enrichment_last_checked_at TIMESTAMP;

ALTER TABLE contacts
    ADD COLUMN IF NOT EXISTS marketing_consent BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS consent_captured_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS consent_source VARCHAR(120),
    ADD COLUMN IF NOT EXISTS privacy_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS data_quality_score INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS enrichment_status VARCHAR(30) NOT NULL DEFAULT 'NOT_ENRICHED',
    ADD COLUMN IF NOT EXISTS enrichment_last_checked_at TIMESTAMP;

ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS privacy_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS data_quality_score INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS enrichment_status VARCHAR(30) NOT NULL DEFAULT 'NOT_ENRICHED',
    ADD COLUMN IF NOT EXISTS enrichment_last_checked_at TIMESTAMP;
